<?php

namespace App\Services;

class TimeZone
{
  // data from https://timezonedb.com/time-zones
  static public $timezones = [
    'AD' => ['name' => 'Andorra', 'timezone' => 'Europe/Andorra', 'gmt-offset' => 'UTC +02:00'],
    'AE' => ['name' => 'United Arab Emirates', 'timezone' => 'Asia/Dubai', 'gmt-offset' => 'UTC +04:00'],
    'AF' => ['name' => 'Afghanistan', 'timezone' => 'Asia/Kabul', 'gmt-offset' => 'UTC +04:30'],
    'AG' => ['name' => 'Antigua and Barbuda', 'timezone' => 'America/Antigua', 'gmt-offset' => 'UTC -04:00'],
    'AI' => ['name' => 'Anguilla', 'timezone' => 'America/Anguilla', 'gmt-offset' => 'UTC -04:00'],
    'AL' => ['name' => 'Albania', 'timezone' => 'Europe/Tirane', 'gmt-offset' => 'UTC +02:00'],
    'AM' => ['name' => 'Armenia', 'timezone' => 'Asia/Yerevan', 'gmt-offset' => 'UTC +04:00'],
    'AO' => ['name' => 'Angola', 'timezone' => 'Africa/Luanda', 'gmt-offset' => 'UTC +01:00'],
    // 'AQ' => ['name' => 'Antarctica', 'timezone' => 'Antarctica/Casey', 'gmt-offset' => 'UTC +11:00'],
    // 'AQ' => ['name' => 'Antarctica', 'timezone' => 'Antarctica/Davis', 'gmt-offset' => 'UTC +07:00'],
    // 'AQ' => ['name' => 'Antarctica', 'timezone' => 'Antarctica/DumontDUrville', 'gmt-offset' => 'UTC +10:00'],
    // 'AQ' => ['name' => 'Antarctica', 'timezone' => 'Antarctica/Mawson', 'gmt-offset' => 'UTC +05:00'],
    // 'AQ' => ['name' => 'Antarctica', 'timezone' => 'Antarctica/McMurdo', 'gmt-offset' => 'UTC +12:00'],
    // 'AQ' => ['name' => 'Antarctica', 'timezone' => 'Antarctica/Palmer', 'gmt-offset' => 'UTC -03:00'],
    // 'AQ' => ['name' => 'Antarctica', 'timezone' => 'Antarctica/Rothera', 'gmt-offset' => 'UTC -03:00'],
    // 'AQ' => ['name' => 'Antarctica', 'timezone' => 'Antarctica/Syowa', 'gmt-offset' => 'UTC +03:00'],
    // 'AQ' => ['name' => 'Antarctica', 'timezone' => 'Antarctica/Troll', 'gmt-offset' => 'UTC +02:00'],
    // 'AQ' => ['name' => 'Antarctica', 'timezone' => 'Antarctica/Vostok', 'gmt-offset' => 'UTC +06:00'],
    'AR' => ['name' => 'Argentina', 'timezone' => 'America/Argentina/Buenos_Aires', 'gmt-offset' => 'UTC -03:00'],
    // 'AR' => ['name' => 'Argentina', 'timezone' => 'America/Argentina/Catamarca', 'gmt-offset' => 'UTC -03:00'],
    // 'AR' => ['name' => 'Argentina', 'timezone' => 'America/Argentina/Cordoba', 'gmt-offset' => 'UTC -03:00'],
    // 'AR' => ['name' => 'Argentina', 'timezone' => 'America/Argentina/Jujuy', 'gmt-offset' => 'UTC -03:00'],
    // 'AR' => ['name' => 'Argentina', 'timezone' => 'America/Argentina/La_Rioja', 'gmt-offset' => 'UTC -03:00'],
    // 'AR' => ['name' => 'Argentina', 'timezone' => 'America/Argentina/Mendoza', 'gmt-offset' => 'UTC -03:00'],
    // 'AR' => ['name' => 'Argentina', 'timezone' => 'America/Argentina/Rio_Gallegos', 'gmt-offset' => 'UTC -03:00'],
    // 'AR' => ['name' => 'Argentina', 'timezone' => 'America/Argentina/Salta', 'gmt-offset' => 'UTC -03:00'],
    // 'AR' => ['name' => 'Argentina', 'timezone' => 'America/Argentina/San_Juan', 'gmt-offset' => 'UTC -03:00'],
    // 'AR' => ['name' => 'Argentina', 'timezone' => 'America/Argentina/San_Luis', 'gmt-offset' => 'UTC -03:00'],
    // 'AR' => ['name' => 'Argentina', 'timezone' => 'America/Argentina/Tucuman', 'gmt-offset' => 'UTC -03:00'],
    // 'AR' => ['name' => 'Argentina', 'timezone' => 'America/Argentina/Ushuaia', 'gmt-offset' => 'UTC -03:00'],
    'AS' => ['name' => 'American Samoa', 'timezone' => 'Pacific/Pago_Pago', 'gmt-offset' => 'UTC -11:00'],
    'AT' => ['name' => 'Austria', 'timezone' => 'Europe/Vienna', 'gmt-offset' => 'UTC +02:00'],
    // 'AU' => ['name' => 'Australia', 'timezone' => 'Antarctica/Macquarie', 'gmt-offset' => 'UTC +10:00'],
    // 'AU' => ['name' => 'Australia', 'timezone' => 'Australia/Adelaide', 'gmt-offset' => 'UTC +09:30'],
    // 'AU' => ['name' => 'Australia', 'timezone' => 'Australia/Brisbane', 'gmt-offset' => 'UTC +10:00'],
    // 'AU' => ['name' => 'Australia', 'timezone' => 'Australia/Broken_Hill', 'gmt-offset' => 'UTC +09:30'],
    // 'AU' => ['name' => 'Australia', 'timezone' => 'Australia/Darwin', 'gmt-offset' => 'UTC +09:30'],
    // 'AU' => ['name' => 'Australia', 'timezone' => 'Australia/Eucla', 'gmt-offset' => 'UTC +08:45'],
    // 'AU' => ['name' => 'Australia', 'timezone' => 'Australia/Hobart', 'gmt-offset' => 'UTC +10:00'],
    // 'AU' => ['name' => 'Australia', 'timezone' => 'Australia/Lindeman', 'gmt-offset' => 'UTC +10:00'],
    // 'AU' => ['name' => 'Australia', 'timezone' => 'Australia/Lord_Howe', 'gmt-offset' => 'UTC +10:30'],
    'AU' => ['name' => 'Australia', 'timezone' => 'Australia/Melbourne', 'gmt-offset' => 'UTC +10:00'],
    // 'AU' => ['name' => 'Australia', 'timezone' => 'Australia/Perth', 'gmt-offset' => 'UTC +08:00'],
    // 'AU' => ['name' => 'Australia', 'timezone' => 'Australia/Sydney', 'gmt-offset' => 'UTC +10:00'],
    'AW' => ['name' => 'Aruba', 'timezone' => 'America/Aruba', 'gmt-offset' => 'UTC -04:00'],
    'AX' => ['name' => 'Åland Islands', 'timezone' => 'Europe/Mariehamn', 'gmt-offset' => 'UTC +03:00'],
    'AZ' => ['name' => 'Azerbaijan', 'timezone' => 'Asia/Baku', 'gmt-offset' => 'UTC +04:00'],
    'BA' => ['name' => 'Bosnia and Herzegovina', 'timezone' => 'Europe/Sarajevo', 'gmt-offset' => 'UTC +02:00'],
    'BB' => ['name' => 'Barbados', 'timezone' => 'America/Barbados', 'gmt-offset' => 'UTC -04:00'],
    'BD' => ['name' => 'Bangladesh', 'timezone' => 'Asia/Dhaka', 'gmt-offset' => 'UTC +06:00'],
    'BE' => ['name' => 'Belgium', 'timezone' => 'Europe/Brussels', 'gmt-offset' => 'UTC +02:00'],
    'BF' => ['name' => 'Burkina Faso', 'timezone' => 'Africa/Ouagadougou', 'gmt-offset' => 'UTC'],
    'BG' => ['name' => 'Bulgaria', 'timezone' => 'Europe/Sofia', 'gmt-offset' => 'UTC +03:00'],
    'BH' => ['name' => 'Bahrain', 'timezone' => 'Asia/Bahrain', 'gmt-offset' => 'UTC +03:00'],
    'BI' => ['name' => 'Burundi', 'timezone' => 'Africa/Bujumbura', 'gmt-offset' => 'UTC +02:00'],
    'BJ' => ['name' => 'Benin', 'timezone' => 'Africa/Porto-Novo', 'gmt-offset' => 'UTC +01:00'],
    'BL' => ['name' => 'Saint Barthélemy', 'timezone' => 'America/St_Barthelemy', 'gmt-offset' => 'UTC -04:00'],
    'BM' => ['name' => 'Bermuda', 'timezone' => 'Atlantic/Bermuda', 'gmt-offset' => 'UTC -03:00'],
    'BN' => ['name' => 'Brunei Darussalam', 'timezone' => 'Asia/Brunei', 'gmt-offset' => 'UTC +08:00'],
    'BO' => ['name' => 'Bolivia, Plurinational State of', 'timezone' => 'America/La_Paz', 'gmt-offset' => 'UTC -04:00'],
    'BQ' => ['name' => 'Bonaire, Sint Eustatius and Saba', 'timezone' => 'America/Kralendijk', 'gmt-offset' => 'UTC -04:00'],
    // 'BR' => ['name' => 'Brazil', 'timezone' => 'America/Araguaina', 'gmt-offset' => 'UTC -03:00'],
    // 'BR' => ['name' => 'Brazil', 'timezone' => 'America/Bahia', 'gmt-offset' => 'UTC -03:00'],
    // 'BR' => ['name' => 'Brazil', 'timezone' => 'America/Belem', 'gmt-offset' => 'UTC -03:00'],
    // 'BR' => ['name' => 'Brazil', 'timezone' => 'America/Boa_Vista', 'gmt-offset' => 'UTC -04:00'],
    // 'BR' => ['name' => 'Brazil', 'timezone' => 'America/Campo_Grande', 'gmt-offset' => 'UTC -04:00'],
    // 'BR' => ['name' => 'Brazil', 'timezone' => 'America/Cuiaba', 'gmt-offset' => 'UTC -04:00'],
    // 'BR' => ['name' => 'Brazil', 'timezone' => 'America/Eirunepe', 'gmt-offset' => 'UTC -05:00'],
    // 'BR' => ['name' => 'Brazil', 'timezone' => 'America/Fortaleza', 'gmt-offset' => 'UTC -03:00'],
    // 'BR' => ['name' => 'Brazil', 'timezone' => 'America/Maceio', 'gmt-offset' => 'UTC -03:00'],
    // 'BR' => ['name' => 'Brazil', 'timezone' => 'America/Manaus', 'gmt-offset' => 'UTC -04:00'],
    // 'BR' => ['name' => 'Brazil', 'timezone' => 'America/Noronha', 'gmt-offset' => 'UTC -02:00'],
    // 'BR' => ['name' => 'Brazil', 'timezone' => 'America/Porto_Velho', 'gmt-offset' => 'UTC -04:00'],
    // 'BR' => ['name' => 'Brazil', 'timezone' => 'America/Recife', 'gmt-offset' => 'UTC -03:00'],
    // 'BR' => ['name' => 'Brazil', 'timezone' => 'America/Rio_Branco', 'gmt-offset' => 'UTC -05:00'],
    // 'BR' => ['name' => 'Brazil', 'timezone' => 'America/Santarem', 'gmt-offset' => 'UTC -03:00'],
    'BR' => ['name' => 'Brazil', 'timezone' => 'America/Sao_Paulo', 'gmt-offset' => 'UTC -03:00'],
    'BS' => ['name' => 'Bahamas', 'timezone' => 'America/Nassau', 'gmt-offset' => 'UTC -04:00'],
    'BT' => ['name' => 'Bhutan', 'timezone' => 'Asia/Thimphu', 'gmt-offset' => 'UTC +06:00'],
    'BW' => ['name' => 'Botswana', 'timezone' => 'Africa/Gaborone', 'gmt-offset' => 'UTC +02:00'],
    'BY' => ['name' => 'Belarus', 'timezone' => 'Europe/Minsk', 'gmt-offset' => 'UTC +03:00'],
    'BZ' => ['name' => 'Belize', 'timezone' => 'America/Belize', 'gmt-offset' => 'UTC -06:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Atikokan', 'gmt-offset' => 'UTC -05:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Blanc-Sablon', 'gmt-offset' => 'UTC -04:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Cambridge_Bay', 'gmt-offset' => 'UTC -06:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Creston', 'gmt-offset' => 'UTC -07:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Dawson_Creek', 'gmt-offset' => 'UTC -07:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Dawson', 'gmt-offset' => 'UTC -07:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Edmonton', 'gmt-offset' => 'UTC -06:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Fort_Nelson', 'gmt-offset' => 'UTC -07:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Glace_Bay', 'gmt-offset' => 'UTC -03:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Goose_Bay', 'gmt-offset' => 'UTC -03:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Halifax', 'gmt-offset' => 'UTC -03:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Inuvik', 'gmt-offset' => 'UTC -06:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Iqaluit', 'gmt-offset' => 'UTC -04:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Moncton', 'gmt-offset' => 'UTC -03:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Rankin_Inlet', 'gmt-offset' => 'UTC -05:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Regina', 'gmt-offset' => 'UTC -06:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Resolute', 'gmt-offset' => 'UTC -05:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/St_Johns', 'gmt-offset' => 'UTC -02:30'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Swift_Current', 'gmt-offset' => 'UTC -06:00'],
    'CA' => ['name' => 'Canada', 'timezone' => 'America/Toronto', 'gmt-offset' => 'UTC -04:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Vancouver', 'gmt-offset' => 'UTC -07:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Whitehorse', 'gmt-offset' => 'UTC -07:00'],
    // 'CA' => ['name' => 'Canada', 'timezone' => 'America/Winnipeg', 'gmt-offset' => 'UTC -05:00'],
    'CC' => ['name' => 'Cocos (Keeling) Islands', 'timezone' => 'Indian/Cocos', 'gmt-offset' => 'UTC +06:30'],
    'CD' => ['name' => 'Congo, the Democratic Republic of the', 'timezone' => 'Africa/Kinshasa', 'gmt-offset' => 'UTC +01:00'],
    // 'CD' => ['name' => 'Congo, the Democratic Republic of the', 'timezone' => 'Africa/Lubumbashi', 'gmt-offset' => 'UTC +02:00'],
    'CF' => ['name' => 'Central African Republic', 'timezone' => 'Africa/Bangui', 'gmt-offset' => 'UTC +01:00'],
    'CG' => ['name' => 'Congo', 'timezone' => 'Africa/Brazzaville', 'gmt-offset' => 'UTC +01:00'],
    'CH' => ['name' => 'Switzerland', 'timezone' => 'Europe/Zurich', 'gmt-offset' => 'UTC +02:00'],
    'CI' => ['name' => 'Côte dIvoire', 'timezone' => 'Africa/Abidjan', 'gmt-offset' => 'UTC'],
    'CK' => ['name' => 'Cook Islands', 'timezone' => 'Pacific/Rarotonga', 'gmt-offset' => 'UTC -10:00'],
    // 'CL' => ['name' => 'Chile', 'timezone' => 'America/Punta_Arenas', 'gmt-offset' => 'UTC -03:00'],
    'CL' => ['name' => 'Chile', 'timezone' => 'America/Santiago', 'gmt-offset' => 'UTC -04:00'],
    // 'CL' => ['name' => 'Chile', 'timezone' => 'Pacific/Easter', 'gmt-offset' => 'UTC -06:00'],
    'CM' => ['name' => 'Cameroon', 'timezone' => 'Africa/Douala', 'gmt-offset' => 'UTC +01:00'],
    'CN' => ['name' => 'China', 'timezone' => 'Asia/Shanghai', 'gmt-offset' => 'UTC +08:00'],
    // 'CN' => ['name' => 'China', 'timezone' => 'Asia/Urumqi', 'gmt-offset' => 'UTC +06:00'],
    'CO' => ['name' => 'Colombia', 'timezone' => 'America/Bogota', 'gmt-offset' => 'UTC -05:00'],
    'CR' => ['name' => 'Costa Rica', 'timezone' => 'America/Costa_Rica', 'gmt-offset' => 'UTC -06:00'],
    'CU' => ['name' => 'Cuba', 'timezone' => 'America/Havana', 'gmt-offset' => 'UTC -04:00'],
    'CV' => ['name' => 'Cape Verde', 'timezone' => 'Atlantic/Cape_Verde', 'gmt-offset' => 'UTC -01:00'],
    'CW' => ['name' => 'Curaçao', 'timezone' => 'America/Curacao', 'gmt-offset' => 'UTC -04:00'],
    'CX' => ['name' => 'Christmas Island', 'timezone' => 'Indian/Christmas', 'gmt-offset' => 'UTC +07:00'],
    'CY' => ['name' => 'Cyprus', 'timezone' => 'Asia/Famagusta', 'gmt-offset' => 'UTC +03:00'],
    // 'CY' => ['name' => 'Cyprus', 'timezone' => 'Asia/Nicosia', 'gmt-offset' => 'UTC +03:00'],
    'CZ' => ['name' => 'Czech Republic', 'timezone' => 'Europe/Prague', 'gmt-offset' => 'UTC +02:00'],
    'DE' => ['name' => 'Germany', 'timezone' => 'Europe/Berlin', 'gmt-offset' => 'UTC +02:00'],
    // 'DE' => ['name' => 'Germany', 'timezone' => 'Europe/Busingen', 'gmt-offset' => 'UTC +02:00'],
    'DJ' => ['name' => 'Djibouti', 'timezone' => 'Africa/Djibouti', 'gmt-offset' => 'UTC +03:00'],
    'DK' => ['name' => 'Denmark', 'timezone' => 'Europe/Copenhagen', 'gmt-offset' => 'UTC +02:00'],
    'DM' => ['name' => 'Dominica', 'timezone' => 'America/Dominica', 'gmt-offset' => 'UTC -04:00'],
    'DO' => ['name' => 'Dominican Republic', 'timezone' => 'America/Santo_Domingo', 'gmt-offset' => 'UTC -04:00'],
    'DZ' => ['name' => 'Algeria', 'timezone' => 'Africa/Algiers', 'gmt-offset' => 'UTC +01:00'],
    'EC' => ['name' => 'Ecuador', 'timezone' => 'America/Guayaquil', 'gmt-offset' => 'UTC -05:00'],
    // 'EC' => ['name' => 'Ecuador', 'timezone' => 'Pacific/Galapagos', 'gmt-offset' => 'UTC -06:00'],
    'EE' => ['name' => 'Estonia', 'timezone' => 'Europe/Tallinn', 'gmt-offset' => 'UTC +03:00'],
    'EG' => ['name' => 'Egypt', 'timezone' => 'Africa/Cairo', 'gmt-offset' => 'UTC +03:00'],
    'ER' => ['name' => 'Eritrea', 'timezone' => 'Africa/Asmara', 'gmt-offset' => 'UTC +03:00'],
    // 'ES' => ['name' => 'Spain', 'timezone' => 'Africa/Ceuta', 'gmt-offset' => 'UTC +02:00'],
    // 'ES' => ['name' => 'Spain', 'timezone' => 'Atlantic/Canary', 'gmt-offset' => 'UTC +01:00'],
    'ES' => ['name' => 'Spain', 'timezone' => 'Europe/Madrid', 'gmt-offset' => 'UTC +02:00'],
    'ET' => ['name' => 'Ethiopia', 'timezone' => 'Africa/Addis_Ababa', 'gmt-offset' => 'UTC +03:00'],
    'FI' => ['name' => 'Finland', 'timezone' => 'Europe/Helsinki', 'gmt-offset' => 'UTC +03:00'],
    'FJ' => ['name' => 'Fiji', 'timezone' => 'Pacific/Fiji', 'gmt-offset' => 'UTC +12:00'],
    'FK' => ['name' => 'Falkland Islands (Malvinas)', 'timezone' => 'Atlantic/Stanley', 'gmt-offset' => 'UTC -03:00'],
    // 'FM' => ['name' => 'Micronesia, Federated States of', 'timezone' => 'Pacific/Chuuk', 'gmt-offset' => 'UTC +10:00'],
    // 'FM' => ['name' => 'Micronesia, Federated States of', 'timezone' => 'Pacific/Kosrae', 'gmt-offset' => 'UTC +11:00'],
    'FM' => ['name' => 'Micronesia, Federated States of', 'timezone' => 'Pacific/Pohnpei', 'gmt-offset' => 'UTC +11:00'],
    'FO' => ['name' => 'Faroe Islands', 'timezone' => 'Atlantic/Faroe', 'gmt-offset' => 'UTC +01:00'],
    'FR' => ['name' => 'France', 'timezone' => 'Europe/Paris', 'gmt-offset' => 'UTC +02:00'],
    'GA' => ['name' => 'Gabon', 'timezone' => 'Africa/Libreville', 'gmt-offset' => 'UTC +01:00'],
    'GB' => ['name' => 'United Kingdom', 'timezone' => 'Europe/London', 'gmt-offset' => 'UTC +01:00'],
    'GD' => ['name' => 'Grenada', 'timezone' => 'America/Grenada', 'gmt-offset' => 'UTC -04:00'],
    'GE' => ['name' => 'Georgia', 'timezone' => 'Asia/Tbilisi', 'gmt-offset' => 'UTC +04:00'],
    'GF' => ['name' => 'French Guiana', 'timezone' => 'America/Cayenne', 'gmt-offset' => 'UTC -03:00'],
    'GG' => ['name' => 'Guernsey', 'timezone' => 'Europe/Guernsey', 'gmt-offset' => 'UTC +01:00'],
    'GH' => ['name' => 'Ghana', 'timezone' => 'Africa/Accra', 'gmt-offset' => 'UTC'],
    'GI' => ['name' => 'Gibraltar', 'timezone' => 'Europe/Gibraltar', 'gmt-offset' => 'UTC +02:00'],
    'GL' => ['name' => 'Greenland', 'timezone' => 'America/Danmarkshavn', 'gmt-offset' => 'UTC'],
    // 'GL' => ['name' => 'Greenland', 'timezone' => 'America/Nuuk', 'gmt-offset' => 'UTC -02:00'],
    // 'GL' => ['name' => 'Greenland', 'timezone' => 'America/Scoresbysund', 'gmt-offset' => 'UTC'],
    // 'GL' => ['name' => 'Greenland', 'timezone' => 'America/Thule', 'gmt-offset' => 'UTC -03:00'],
    'GM' => ['name' => 'Gambia', 'timezone' => 'Africa/Banjul', 'gmt-offset' => 'UTC'],
    'GN' => ['name' => 'Guinea', 'timezone' => 'Africa/Conakry', 'gmt-offset' => 'UTC'],
    'GP' => ['name' => 'Guadeloupe', 'timezone' => 'America/Guadeloupe', 'gmt-offset' => 'UTC -04:00'],
    'GQ' => ['name' => 'Equatorial Guinea', 'timezone' => 'Africa/Malabo', 'gmt-offset' => 'UTC +01:00'],
    'GR' => ['name' => 'Greece', 'timezone' => 'Europe/Athens', 'gmt-offset' => 'UTC +03:00'],
    'GS' => ['name' => 'South Georgia and the South Sandwich Islands', 'timezone' => 'Atlantic/South_Georgia', 'gmt-offset' => 'UTC -02:00'],
    'GT' => ['name' => 'Guatemala', 'timezone' => 'America/Guatemala', 'gmt-offset' => 'UTC -06:00'],
    'GU' => ['name' => 'Guam', 'timezone' => 'Pacific/Guam', 'gmt-offset' => 'UTC +10:00'],
    'GW' => ['name' => 'Guinea-Bissau', 'timezone' => 'Africa/Bissau', 'gmt-offset' => 'UTC'],
    'GY' => ['name' => 'Guyana', 'timezone' => 'America/Guyana', 'gmt-offset' => 'UTC -04:00'],
    'HK' => ['name' => 'Hong Kong', 'timezone' => 'Asia/Hong_Kong', 'gmt-offset' => 'UTC +08:00'],
    'HN' => ['name' => 'Honduras', 'timezone' => 'America/Tegucigalpa', 'gmt-offset' => 'UTC -06:00'],
    'HR' => ['name' => 'Croatia', 'timezone' => 'Europe/Zagreb', 'gmt-offset' => 'UTC +02:00'],
    'HT' => ['name' => 'Haiti', 'timezone' => 'America/Port-au-Prince', 'gmt-offset' => 'UTC -04:00'],
    'HU' => ['name' => 'Hungary', 'timezone' => 'Europe/Budapest', 'gmt-offset' => 'UTC +02:00'],
    'ID' => ['name' => 'Indonesia', 'timezone' => 'Asia/Jakarta', 'gmt-offset' => 'UTC +07:00'],
    // 'ID' => ['name' => 'Indonesia', 'timezone' => 'Asia/Jayapura', 'gmt-offset' => 'UTC +09:00'],
    // 'ID' => ['name' => 'Indonesia', 'timezone' => 'Asia/Makassar', 'gmt-offset' => 'UTC +08:00'],
    // 'ID' => ['name' => 'Indonesia', 'timezone' => 'Asia/Pontianak', 'gmt-offset' => 'UTC +07:00'],
    'IE' => ['name' => 'Ireland', 'timezone' => 'Europe/Dublin', 'gmt-offset' => 'UTC +01:00'],
    'IL' => ['name' => 'Israel', 'timezone' => 'Asia/Jerusalem', 'gmt-offset' => 'UTC +03:00'],
    'IM' => ['name' => 'Isle of Man', 'timezone' => 'Europe/Isle_of_Man', 'gmt-offset' => 'UTC +01:00'],
    'IN' => ['name' => 'India', 'timezone' => 'Asia/Kolkata', 'gmt-offset' => 'UTC +05:30'],
    'IO' => ['name' => 'British Indian Ocean Territory', 'timezone' => 'Indian/Chagos', 'gmt-offset' => 'UTC +06:00'],
    'IQ' => ['name' => 'Iraq', 'timezone' => 'Asia/Baghdad', 'gmt-offset' => 'UTC +03:00'],
    'IR' => ['name' => 'Iran, Islamic Republic of', 'timezone' => 'Asia/Tehran', 'gmt-offset' => 'UTC +03:30'],
    'IS' => ['name' => 'Iceland', 'timezone' => 'Atlantic/Reykjavik', 'gmt-offset' => 'UTC'],
    'IT' => ['name' => 'Italy', 'timezone' => 'Europe/Rome', 'gmt-offset' => 'UTC +02:00'],
    'JE' => ['name' => 'Jersey', 'timezone' => 'Europe/Jersey', 'gmt-offset' => 'UTC +01:00'],
    'JM' => ['name' => 'Jamaica', 'timezone' => 'America/Jamaica', 'gmt-offset' => 'UTC -05:00'],
    'JO' => ['name' => 'Jordan', 'timezone' => 'Asia/Amman', 'gmt-offset' => 'UTC +03:00'],
    'JP' => ['name' => 'Japan', 'timezone' => 'Asia/Tokyo', 'gmt-offset' => 'UTC +09:00'],
    'KE' => ['name' => 'Kenya', 'timezone' => 'Africa/Nairobi', 'gmt-offset' => 'UTC +03:00'],
    'KG' => ['name' => 'Kyrgyzstan', 'timezone' => 'Asia/Bishkek', 'gmt-offset' => 'UTC +06:00'],
    'KH' => ['name' => 'Cambodia', 'timezone' => 'Asia/Phnom_Penh', 'gmt-offset' => 'UTC +07:00'],
    // 'KI' => ['name' => 'Kiribati', 'timezone' => 'Pacific/Kanton', 'gmt-offset' => 'UTC +13:00'],
    // 'KI' => ['name' => 'Kiribati', 'timezone' => 'Pacific/Kiritimati', 'gmt-offset' => 'UTC +14:00'],
    'KI' => ['name' => 'Kiribati', 'timezone' => 'Pacific/Tarawa', 'gmt-offset' => 'UTC +12:00'],
    'KM' => ['name' => 'Comoros', 'timezone' => 'Indian/Comoro', 'gmt-offset' => 'UTC +03:00'],
    'KN' => ['name' => 'Saint Kitts and Nevis', 'timezone' => 'America/St_Kitts', 'gmt-offset' => 'UTC -04:00'],
    'KP' => ['name' => 'Korea, Democratic People\'s Republic of', 'timezone' => 'Asia/Pyongyang', 'gmt-offset' => 'UTC +09:00'],
    'KR' => ['name' => 'Korea, Republic of', 'timezone' => 'Asia/Seoul', 'gmt-offset' => 'UTC +09:00'],
    'KW' => ['name' => 'Kuwait', 'timezone' => 'Asia/Kuwait', 'gmt-offset' => 'UTC +03:00'],
    'KY' => ['name' => 'Cayman Islands', 'timezone' => 'America/Cayman', 'gmt-offset' => 'UTC -05:00'],
    // 'KZ' => ['name' => 'Kazakhstan', 'timezone' => 'Asia/Almaty', 'gmt-offset' => 'UTC +06:00'],
    // 'KZ' => ['name' => 'Kazakhstan', 'timezone' => 'Asia/Aqtau', 'gmt-offset' => 'UTC +05:00'],
    // 'KZ' => ['name' => 'Kazakhstan', 'timezone' => 'Asia/Aqtobe', 'gmt-offset' => 'UTC +05:00'],
    // 'KZ' => ['name' => 'Kazakhstan', 'timezone' => 'Asia/Atyrau', 'gmt-offset' => 'UTC +05:00'],
    // 'KZ' => ['name' => 'Kazakhstan', 'timezone' => 'Asia/Oral', 'gmt-offset' => 'UTC +05:00'],
    // 'KZ' => ['name' => 'Kazakhstan', 'timezone' => 'Asia/Qostanay', 'gmt-offset' => 'UTC +06:00'],
    'KZ' => ['name' => 'Kazakhstan', 'timezone' => 'Asia/Qyzylorda', 'gmt-offset' => 'UTC +05:00'],
    'LA' => ['name' => 'Lao People\'s Democratic Republic', 'timezone' => 'Asia/Vientiane', 'gmt-offset' => 'UTC +07:00'],
    'LB' => ['name' => 'Lebanon', 'timezone' => 'Asia/Beirut', 'gmt-offset' => 'UTC +03:00'],
    'LC' => ['name' => 'Saint Lucia', 'timezone' => 'America/St_Lucia', 'gmt-offset' => 'UTC -04:00'],
    'LI' => ['name' => 'Liechtenstein', 'timezone' => 'Europe/Vaduz', 'gmt-offset' => 'UTC +02:00'],
    'LK' => ['name' => 'Sri Lanka', 'timezone' => 'Asia/Colombo', 'gmt-offset' => 'UTC +05:30'],
    'LR' => ['name' => 'Liberia', 'timezone' => 'Africa/Monrovia', 'gmt-offset' => 'UTC'],
    'LS' => ['name' => 'Lesotho', 'timezone' => 'Africa/Maseru', 'gmt-offset' => 'UTC +02:00'],
    'LT' => ['name' => 'Lithuania', 'timezone' => 'Europe/Vilnius', 'gmt-offset' => 'UTC +03:00'],
    'LU' => ['name' => 'Luxembourg', 'timezone' => 'Europe/Luxembourg', 'gmt-offset' => 'UTC +02:00'],
    'LV' => ['name' => 'Latvia', 'timezone' => 'Europe/Riga', 'gmt-offset' => 'UTC +03:00'],
    'LY' => ['name' => 'Libya', 'timezone' => 'Africa/Tripoli', 'gmt-offset' => 'UTC +02:00'],
    'MA' => ['name' => 'Morocco', 'timezone' => 'Africa/Casablanca', 'gmt-offset' => 'UTC +01:00'],
    // 'MA' => ['name' => 'Morocco', 'timezone' => 'Africa/El_Aaiun', 'gmt-offset' => 'UTC +01:00'],
    'MC' => ['name' => 'Monaco', 'timezone' => 'Europe/Monaco', 'gmt-offset' => 'UTC +02:00'],
    'MD' => ['name' => 'Moldova, Republic of', 'timezone' => 'Europe/Chisinau', 'gmt-offset' => 'UTC +03:00'],
    'ME' => ['name' => 'Montenegro', 'timezone' => 'Europe/Podgorica', 'gmt-offset' => 'UTC +02:00'],
    // 'MF' => ['name' => 'Saint Martin (French part)', 'timezone' => 'America/Marigot', 'gmt-offset' => 'UTC -04:00'],
    'MG' => ['name' => 'Madagascar', 'timezone' => 'Indian/Antananarivo', 'gmt-offset' => 'UTC +03:00'],
    'MH' => ['name' => 'Marshall Islands', 'timezone' => 'Pacific/Kwajalein', 'gmt-offset' => 'UTC +12:00'],
    // 'MH' => ['name' => 'Marshall Islands', 'timezone' => 'Pacific/Majuro', 'gmt-offset' => 'UTC +12:00'],
    'MK' => ['name' => 'Macedonia, the Former Yugoslav Republic of', 'timezone' => 'Europe/Skopje', 'gmt-offset' => 'UTC +02:00'],
    'ML' => ['name' => 'Mali', 'timezone' => 'Africa/Bamako', 'gmt-offset' => 'UTC'],
    'MM' => ['name' => 'Myanmar', 'timezone' => 'Asia/Yangon', 'gmt-offset' => 'UTC +06:30'],
    'MN' => ['name' => 'Mongolia', 'timezone' => 'Asia/Choibalsan', 'gmt-offset' => 'UTC +08:00'],
    // 'MN' => ['name' => 'Mongolia', 'timezone' => 'Asia/Hovd', 'gmt-offset' => 'UTC +07:00'],
    // 'MN' => ['name' => 'Mongolia', 'timezone' => 'Asia/Ulaanbaatar', 'gmt-offset' => 'UTC +08:00'],
    'MO' => ['name' => 'Macao', 'timezone' => 'Asia/Macau', 'gmt-offset' => 'UTC +08:00'],
    'MP' => ['name' => 'Northern Mariana Islands', 'timezone' => 'Pacific/Saipan', 'gmt-offset' => 'UTC +10:00'],
    'MQ' => ['name' => 'Martinique', 'timezone' => 'America/Martinique', 'gmt-offset' => 'UTC -04:00'],
    'MR' => ['name' => 'Mauritania', 'timezone' => 'Africa/Nouakchott', 'gmt-offset' => 'UTC'],
    'MS' => ['name' => 'Montserrat', 'timezone' => 'America/Montserrat', 'gmt-offset' => 'UTC -04:00'],
    'MT' => ['name' => 'Malta', 'timezone' => 'Europe/Malta', 'gmt-offset' => 'UTC +02:00'],
    'MU' => ['name' => 'Mauritius', 'timezone' => 'Indian/Mauritius', 'gmt-offset' => 'UTC +04:00'],
    'MV' => ['name' => 'Maldives', 'timezone' => 'Indian/Maldives', 'gmt-offset' => 'UTC +05:00'],
    'MW' => ['name' => 'Malawi', 'timezone' => 'Africa/Blantyre', 'gmt-offset' => 'UTC +02:00'],
    // 'MX' => ['name' => 'Mexico', 'timezone' => 'America/Bahia_Banderas', 'gmt-offset' => 'UTC -06:00'],
    // 'MX' => ['name' => 'Mexico', 'timezone' => 'America/Cancun', 'gmt-offset' => 'UTC -05:00'],
    // 'MX' => ['name' => 'Mexico', 'timezone' => 'America/Chihuahua', 'gmt-offset' => 'UTC -06:00'],
    // 'MX' => ['name' => 'Mexico', 'timezone' => 'America/Ciudad_Juarez', 'gmt-offset' => 'UTC -06:00'],
    // 'MX' => ['name' => 'Mexico', 'timezone' => 'America/Hermosillo', 'gmt-offset' => 'UTC -07:00'],
    // 'MX' => ['name' => 'Mexico', 'timezone' => 'America/Matamoros', 'gmt-offset' => 'UTC -05:00'],
    // 'MX' => ['name' => 'Mexico', 'timezone' => 'America/Mazatlan', 'gmt-offset' => 'UTC -07:00'],
    // 'MX' => ['name' => 'Mexico', 'timezone' => 'America/Merida', 'gmt-offset' => 'UTC -06:00'],
    'MX' => ['name' => 'Mexico', 'timezone' => 'America/Mexico_City', 'gmt-offset' => 'UTC -06:00'],
    // 'MX' => ['name' => 'Mexico', 'timezone' => 'America/Monterrey', 'gmt-offset' => 'UTC -06:00'],
    // 'MX' => ['name' => 'Mexico', 'timezone' => 'America/Ojinaga', 'gmt-offset' => 'UTC -05:00'],
    // 'MX' => ['name' => 'Mexico', 'timezone' => 'America/Tijuana', 'gmt-offset' => 'UTC -07:00'],
    'MY' => ['name' => 'Malaysia', 'timezone' => 'Asia/Kuala_Lumpur', 'gmt-offset' => 'UTC +08:00'],
    // 'MY' => ['name' => 'Malaysia', 'timezone' => 'Asia/Kuching', 'gmt-offset' => 'UTC +08:00'],
    'MZ' => ['name' => 'Mozambique', 'timezone' => 'Africa/Maputo', 'gmt-offset' => 'UTC +02:00'],
    'NA' => ['name' => 'Namibia', 'timezone' => 'Africa/Windhoek', 'gmt-offset' => 'UTC +02:00'],
    'NC' => ['name' => 'New Caledonia', 'timezone' => 'Pacific/Noumea', 'gmt-offset' => 'UTC +11:00'],
    'NE' => ['name' => 'Niger', 'timezone' => 'Africa/Niamey', 'gmt-offset' => 'UTC +01:00'],
    'NF' => ['name' => 'Norfolk Island', 'timezone' => 'Pacific/Norfolk', 'gmt-offset' => 'UTC +11:00'],
    'NG' => ['name' => 'Nigeria', 'timezone' => 'Africa/Lagos', 'gmt-offset' => 'UTC +01:00'],
    'NI' => ['name' => 'Nicaragua', 'timezone' => 'America/Managua', 'gmt-offset' => 'UTC -06:00'],
    'NL' => ['name' => 'Netherlands', 'timezone' => 'Europe/Amsterdam', 'gmt-offset' => 'UTC +02:00'],
    'NO' => ['name' => 'Norway', 'timezone' => 'Europe/Oslo', 'gmt-offset' => 'UTC +02:00'],
    'NP' => ['name' => 'Nepal', 'timezone' => 'Asia/Kathmandu', 'gmt-offset' => 'UTC +05:45'],
    'NR' => ['name' => 'Nauru', 'timezone' => 'Pacific/Nauru', 'gmt-offset' => 'UTC +12:00'],
    'NU' => ['name' => 'Niue', 'timezone' => 'Pacific/Niue', 'gmt-offset' => 'UTC -11:00'],
    'NZ' => ['name' => 'New Zealand', 'timezone' => 'Pacific/Auckland', 'gmt-offset' => 'UTC +12:00'],
    // 'NZ' => ['name' => 'New Zealand', 'timezone' => 'Pacific/Chatham', 'gmt-offset' => 'UTC +12:45'],
    'OM' => ['name' => 'Oman', 'timezone' => 'Asia/Muscat', 'gmt-offset' => 'UTC +04:00'],
    'PA' => ['name' => 'Panama', 'timezone' => 'America/Panama', 'gmt-offset' => 'UTC -05:00'],
    'PE' => ['name' => 'Peru', 'timezone' => 'America/Lima', 'gmt-offset' => 'UTC -05:00'],
    // 'PF' => ['name' => 'French Polynesia', 'timezone' => 'Pacific/Gambier', 'gmt-offset' => 'UTC -09:00'],
    // 'PF' => ['name' => 'French Polynesia', 'timezone' => 'Pacific/Marquesas', 'gmt-offset' => 'UTC -09:30'],
    'PF' => ['name' => 'French Polynesia', 'timezone' => 'Pacific/Tahiti', 'gmt-offset' => 'UTC -10:00'],
    // 'PG' => ['name' => 'Papua New Guinea', 'timezone' => 'Pacific/Bougainville', 'gmt-offset' => 'UTC +11:00'],
    'PG' => ['name' => 'Papua New Guinea', 'timezone' => 'Pacific/Port_Moresby', 'gmt-offset' => 'UTC +10:00'],
    'PH' => ['name' => 'Philippines', 'timezone' => 'Asia/Manila', 'gmt-offset' => 'UTC +08:00'],
    'PK' => ['name' => 'Pakistan', 'timezone' => 'Asia/Karachi', 'gmt-offset' => 'UTC +05:00'],
    'PL' => ['name' => 'Poland', 'timezone' => 'Europe/Warsaw', 'gmt-offset' => 'UTC +02:00'],
    'PM' => ['name' => 'Saint Pierre and Miquelon', 'timezone' => 'America/Miquelon', 'gmt-offset' => 'UTC -02:00'],
    'PN' => ['name' => 'Pitcairn', 'timezone' => 'Pacific/Pitcairn', 'gmt-offset' => 'UTC -08:00'],
    'PR' => ['name' => 'Puerto Rico', 'timezone' => 'America/Puerto_Rico', 'gmt-offset' => 'UTC -04:00'],
    'PS' => ['name' => 'Palestine, State of', 'timezone' => 'Asia/Gaza', 'gmt-offset' => 'UTC +03:00'],
    // 'PS' => ['name' => 'Palestine, State of', 'timezone' => 'Asia/Hebron', 'gmt-offset' => 'UTC +03:00'],
    // 'PT' => ['name' => 'Portugal', 'timezone' => 'Atlantic/Azores', 'gmt-offset' => 'UTC'],
    // 'PT' => ['name' => 'Portugal', 'timezone' => 'Atlantic/Madeira', 'gmt-offset' => 'UTC +01:00'],
    'PT' => ['name' => 'Portugal', 'timezone' => 'Europe/Lisbon', 'gmt-offset' => 'UTC +01:00'],
    'PW' => ['name' => 'Palau', 'timezone' => 'Pacific/Palau', 'gmt-offset' => 'UTC +09:00'],
    'PY' => ['name' => 'Paraguay', 'timezone' => 'America/Asuncion', 'gmt-offset' => 'UTC -04:00'],
    'QA' => ['name' => 'Qatar', 'timezone' => 'Asia/Qatar', 'gmt-offset' => 'UTC +03:00'],
    'RE' => ['name' => 'Réunion', 'timezone' => 'Indian/Reunion', 'gmt-offset' => 'UTC +04:00'],
    'RO' => ['name' => 'Romania', 'timezone' => 'Europe/Bucharest', 'gmt-offset' => 'UTC +03:00'],
    'RS' => ['name' => 'Serbia', 'timezone' => 'Europe/Belgrade', 'gmt-offset' => 'UTC +02:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Asia/Anadyr', 'gmt-offset' => 'UTC +12:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Asia/Barnaul', 'gmt-offset' => 'UTC +07:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Asia/Chita', 'gmt-offset' => 'UTC +09:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Asia/Irkutsk', 'gmt-offset' => 'UTC +08:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Asia/Kamchatka', 'gmt-offset' => 'UTC +12:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Asia/Khandyga', 'gmt-offset' => 'UTC +09:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Asia/Krasnoyarsk', 'gmt-offset' => 'UTC +07:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Asia/Magadan', 'gmt-offset' => 'UTC +11:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Asia/Novokuznetsk', 'gmt-offset' => 'UTC +07:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Asia/Novosibirsk', 'gmt-offset' => 'UTC +07:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Asia/Omsk', 'gmt-offset' => 'UTC +06:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Asia/Sakhalin', 'gmt-offset' => 'UTC +11:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Asia/Srednekolymsk', 'gmt-offset' => 'UTC +11:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Asia/Tomsk', 'gmt-offset' => 'UTC +07:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Asia/Ust-Nera', 'gmt-offset' => 'UTC +10:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Asia/Vladivostok', 'gmt-offset' => 'UTC +10:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Asia/Yakutsk', 'gmt-offset' => 'UTC +09:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Asia/Yekaterinburg', 'gmt-offset' => 'UTC +05:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Europe/Astrakhan', 'gmt-offset' => 'UTC +04:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Europe/Kaliningrad', 'gmt-offset' => 'UTC +02:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Europe/Kirov', 'gmt-offset' => 'UTC +03:00'],
    'RU' => ['name' => 'Russian Federation', 'timezone' => 'Europe/Moscow', 'gmt-offset' => 'UTC +03:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Europe/Samara', 'gmt-offset' => 'UTC +04:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Europe/Saratov', 'gmt-offset' => 'UTC +04:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Europe/Ulyanovsk', 'gmt-offset' => 'UTC +04:00'],
    // 'RU' => ['name' => 'Russian Federation', 'timezone' => 'Europe/Volgograd', 'gmt-offset' => 'UTC +03:00'],
    'RW' => ['name' => 'Rwanda', 'timezone' => 'Africa/Kigali', 'gmt-offset' => 'UTC +02:00'],
    'SA' => ['name' => 'Saudi Arabia', 'timezone' => 'Asia/Riyadh', 'gmt-offset' => 'UTC +03:00'],
    'SB' => ['name' => 'Solomon Islands', 'timezone' => 'Pacific/Guadalcanal', 'gmt-offset' => 'UTC +11:00'],
    'SC' => ['name' => 'Seychelles', 'timezone' => 'Indian/Mahe', 'gmt-offset' => 'UTC +04:00'],
    'SD' => ['name' => 'Sudan', 'timezone' => 'Africa/Khartoum', 'gmt-offset' => 'UTC +02:00'],
    'SE' => ['name' => 'Sweden', 'timezone' => 'Europe/Stockholm', 'gmt-offset' => 'UTC +02:00'],
    'SG' => ['name' => 'Singapore', 'timezone' => 'Asia/Singapore', 'gmt-offset' => 'UTC +08:00'],
    'SH' => ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'timezone' => 'Atlantic/St_Helena', 'gmt-offset' => 'UTC'],
    'SI' => ['name' => 'Slovenia', 'timezone' => 'Europe/Ljubljana', 'gmt-offset' => 'UTC +02:00'],
    'SJ' => ['name' => 'Svalbard and Jan Mayen', 'timezone' => 'Arctic/Longyearbyen', 'gmt-offset' => 'UTC +02:00'],
    'SK' => ['name' => 'Slovakia', 'timezone' => 'Europe/Bratislava', 'gmt-offset' => 'UTC +02:00'],
    'SL' => ['name' => 'Sierra Leone', 'timezone' => 'Africa/Freetown', 'gmt-offset' => 'UTC'],
    'SM' => ['name' => 'San Marino', 'timezone' => 'Europe/San_Marino', 'gmt-offset' => 'UTC +02:00'],
    'SN' => ['name' => 'Senegal', 'timezone' => 'Africa/Dakar', 'gmt-offset' => 'UTC'],
    'SO' => ['name' => 'Somalia', 'timezone' => 'Africa/Mogadishu', 'gmt-offset' => 'UTC +03:00'],
    'SR' => ['name' => 'Suriname', 'timezone' => 'America/Paramaribo', 'gmt-offset' => 'UTC -03:00'],
    'SS' => ['name' => 'South Sudan', 'timezone' => 'Africa/Juba', 'gmt-offset' => 'UTC +02:00'],
    'ST' => ['name' => 'Sao Tome and Principe', 'timezone' => 'Africa/Sao_Tome', 'gmt-offset' => 'UTC'],
    'SV' => ['name' => 'El Salvador', 'timezone' => 'America/El_Salvador', 'gmt-offset' => 'UTC -06:00'],
    'SX' => ['name' => 'Sint Maarten (Dutch part)', 'timezone' => 'America/Lower_Princes', 'gmt-offset' => 'UTC -04:00'],
    'SY' => ['name' => 'Syrian Arab Republic', 'timezone' => 'Asia/Damascus', 'gmt-offset' => 'UTC +03:00'],
    'SZ' => ['name' => 'Swaziland', 'timezone' => 'Africa/Mbabane', 'gmt-offset' => 'UTC +02:00'],
    'TC' => ['name' => 'Turks and Caicos Islands', 'timezone' => 'America/Grand_Turk', 'gmt-offset' => 'UTC -04:00'],
    'TD' => ['name' => 'Chad', 'timezone' => 'Africa/Ndjamena', 'gmt-offset' => 'UTC +01:00'],
    'TF' => ['name' => 'French Southern Territories', 'timezone' => 'Indian/Kerguelen', 'gmt-offset' => 'UTC +05:00'],
    'TG' => ['name' => 'Togo', 'timezone' => 'Africa/Lome', 'gmt-offset' => 'UTC'],
    'TH' => ['name' => 'Thailand', 'timezone' => 'Asia/Bangkok', 'gmt-offset' => 'UTC +07:00'],
    'TJ' => ['name' => 'Tajikistan', 'timezone' => 'Asia/Dushanbe', 'gmt-offset' => 'UTC +05:00'],
    'TK' => ['name' => 'Tokelau', 'timezone' => 'Pacific/Fakaofo', 'gmt-offset' => 'UTC +13:00'],
    'TL' => ['name' => 'Timor-Leste', 'timezone' => 'Asia/Dili', 'gmt-offset' => 'UTC +09:00'],
    'TM' => ['name' => 'Turkmenistan', 'timezone' => 'Asia/Ashgabat', 'gmt-offset' => 'UTC +05:00'],
    'TN' => ['name' => 'Tunisia', 'timezone' => 'Africa/Tunis', 'gmt-offset' => 'UTC +01:00'],
    'TO' => ['name' => 'Tonga', 'timezone' => 'Pacific/Tongatapu', 'gmt-offset' => 'UTC +13:00'],
    'TR' => ['name' => 'Turkey', 'timezone' => 'Europe/Istanbul', 'gmt-offset' => 'UTC +03:00'],
    'TT' => ['name' => 'Trinidad and Tobago', 'timezone' => 'America/Port_of_Spain', 'gmt-offset' => 'UTC -04:00'],
    'TV' => ['name' => 'Tuvalu', 'timezone' => 'Pacific/Funafuti', 'gmt-offset' => 'UTC +12:00'],
    'TW' => ['name' => 'Taiwan, Province of China', 'timezone' => 'Asia/Taipei', 'gmt-offset' => 'UTC +08:00'],
    'TZ' => ['name' => 'Tanzania, United Republic of', 'timezone' => 'Africa/Dar_es_Salaam', 'gmt-offset' => 'UTC +03:00'],
    'UA' => ['name' => 'Ukraine', 'timezone' => 'Europe/Kyiv', 'gmt-offset' => 'UTC +03:00'],
    // 'UA' => ['name' => 'Ukraine', 'timezone' => 'Europe/Simferopol', 'gmt-offset' => 'UTC +03:00'],
    'UG' => ['name' => 'Uganda', 'timezone' => 'Africa/Kampala', 'gmt-offset' => 'UTC +03:00'],
    'UM' => ['name' => 'United States Minor Outlying Islands', 'timezone' => 'Pacific/Midway', 'gmt-offset' => 'UTC -11:00'],
    // 'UM' => ['name' => 'United States Minor Outlying Islands', 'timezone' => 'Pacific/Wake', 'gmt-offset' => 'UTC +12:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Adak', 'gmt-offset' => 'UTC -09:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Anchorage', 'gmt-offset' => 'UTC -08:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Boise', 'gmt-offset' => 'UTC -06:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Chicago', 'gmt-offset' => 'UTC -05:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Denver', 'gmt-offset' => 'UTC -06:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Detroit', 'gmt-offset' => 'UTC -04:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Indiana/Indianapolis', 'gmt-offset' => 'UTC -04:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Indiana/Knox', 'gmt-offset' => 'UTC -05:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Indiana/Marengo', 'gmt-offset' => 'UTC -04:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Indiana/Petersburg', 'gmt-offset' => 'UTC -04:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Indiana/Tell_City', 'gmt-offset' => 'UTC -05:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Indiana/Vevay', 'gmt-offset' => 'UTC -04:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Indiana/Vincennes', 'gmt-offset' => 'UTC -04:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Indiana/Winamac', 'gmt-offset' => 'UTC -04:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Juneau', 'gmt-offset' => 'UTC -08:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Kentucky/Louisville', 'gmt-offset' => 'UTC -04:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Kentucky/Monticello', 'gmt-offset' => 'UTC -04:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Los_Angeles', 'gmt-offset' => 'UTC -07:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Menominee', 'gmt-offset' => 'UTC -05:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Metlakatla', 'gmt-offset' => 'UTC -08:00'],
    'US' => ['name' => 'United States', 'timezone' => 'America/New_York', 'gmt-offset' => 'UTC -04:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Nome', 'gmt-offset' => 'UTC -08:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/North_Dakota/Beulah', 'gmt-offset' => 'UTC -05:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/North_Dakota/Center', 'gmt-offset' => 'UTC -05:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/North_Dakota/New_Salem', 'gmt-offset' => 'UTC -05:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Phoenix', 'gmt-offset' => 'UTC -07:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Sitka', 'gmt-offset' => 'UTC -08:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'America/Yakutat', 'gmt-offset' => 'UTC -08:00'],
    // 'US' => ['name' => 'United States', 'timezone' => 'Pacific/Honolulu', 'gmt-offset' => 'UTC -10:00'],
    'UY' => ['name' => 'Uruguay', 'timezone' => 'America/Montevideo', 'gmt-offset' => 'UTC -03:00'],
    'UZ' => ['name' => 'Uzbekistan', 'timezone' => 'Asia/Samarkand', 'gmt-offset' => 'UTC +05:00'],
    // 'UZ' => ['name' => 'Uzbekistan', 'timezone' => 'Asia/Tashkent', 'gmt-offset' => 'UTC +05:00'],
    'VA' => ['name' => 'Holy See (Vatican City State)', 'timezone' => 'Europe/Vatican', 'gmt-offset' => 'UTC +02:00'],
    'VC' => ['name' => 'Saint Vincent and the Grenadines', 'timezone' => 'America/St_Vincent', 'gmt-offset' => 'UTC -04:00'],
    'VE' => ['name' => 'Venezuela, Bolivarian Republic of', 'timezone' => 'America/Caracas', 'gmt-offset' => 'UTC -04:00'],
    'VG' => ['name' => 'Virgin Islands, British', 'timezone' => 'America/Tortola', 'gmt-offset' => 'UTC -04:00'],
    'VI' => ['name' => 'Virgin Islands, U.S.', 'timezone' => 'America/St_Thomas', 'gmt-offset' => 'UTC -04:00'],
    'VN' => ['name' => 'Viet Nam', 'timezone' => 'Asia/Ho_Chi_Minh', 'gmt-offset' => 'UTC +07:00'],
    'VU' => ['name' => 'Vanuatu', 'timezone' => 'Pacific/Efate', 'gmt-offset' => 'UTC +11:00'],
    'WF' => ['name' => 'Wallis and Futuna', 'timezone' => 'Pacific/Wallis', 'gmt-offset' => 'UTC +12:00'],
    'WS' => ['name' => 'Samoa', 'timezone' => 'Pacific/Apia', 'gmt-offset' => 'UTC +13:00'],
    'YE' => ['name' => 'Yemen', 'timezone' => 'Asia/Aden', 'gmt-offset' => 'UTC +03:00'],
    'YT' => ['name' => 'Mayotte', 'timezone' => 'Indian/Mayotte', 'gmt-offset' => 'UTC +03:00'],
    'ZA' => ['name' => 'South Africa', 'timezone' => 'Africa/Johannesburg', 'gmt-offset' => 'UTC +02:00'],
    'ZM' => ['name' => 'Zambia', 'timezone' => 'Africa/Lusaka', 'gmt-offset' => 'UTC +02:00'],
    'ZW' => ['name' => 'Zimbabwe', 'timezone' => 'Africa/Harare', 'gmt-offset' => 'UTC +02:00'],
  ];

  static public function default(string $code): string
  {
    return self::$timezones[$code]['timezone'] ?? 'UTC';
  }
}
