version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.Nginx
      args:
        - domain_customer=software.localhost
        - php_fpm_host=main
    restart: always
    image: localhost/siser/nginx:${DEV_VERSION:-9.9.9}-local
    ports:
      - 8080:80
    volumes:
      - public:/var/www/html/public
    links:
      - main
    depends_on:
      - main

  main:
    build:
      context: .
      dockerfile: docker/Dockerfile.FPM
      args:
        - frontend_customer=localhost/siser/frontend-customer:${DEV_VERSION:-9.9.9}-local
        - frontend_admin=localhost/siser/frontend-admin:${DEV_VERSION:-9.9.9}-local
    restart: always
    image: localhost/siser/main:${DEV_VERSION:-9.9.9}-web-local
    environment:
      - APP_URL=http://software.localhost
      - CONTAINER_ROLE=main
      - DB_HOST=host.docker.internal
      - DOMAIN_CUSTOMER=software.localhost
      - MAIL_HOST=host.docker.internal
      - QUEUE_CONNECTION=database
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - public:/var/www/html/public

  queue:
    build:
      context: .
      dockerfile: docker/Dockerfile.CLI
      tags:
        - localhost/siser/main:${DEV_VERSION:-9.9.9}-queue-local
        - localhost/siser/main:${DEV_VERSION:-9.9.9}-scheduler-local
    restart: always
    image: localhost/siser/main:${DEV_VERSION:-9.9.9}-queue-local
    environment:
      - CONTAINER_ROLE=queue
      - DB_HOST=host.docker.internal
      - MAIL_HOST=host.docker.internal
      - QUEUE_CONNECTION=database
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  public:
