<?php

use App\Models\Plan;

return [
  'supported_countries' => [
    'AX' => ['name' => 'Åland Islands', 'required_address_information' => []],
    'AL' => ['name' => 'Albania', 'required_address_information' => []],
    'DZ' => ['name' => 'Algeria', 'required_address_information' => []],
    'AS' => ['name' => 'American Samoa', 'required_address_information' => []],
    'AD' => ['name' => 'Andorra', 'required_address_information' => []],
    'AO' => ['name' => 'Angola', 'required_address_information' => []],
    'AI' => ['name' => 'Anguilla', 'required_address_information' => []],
    'AG' => ['name' => 'Antigua and Barbuda', 'required_address_information' => []],
    'AR' => ['name' => 'Argentina', 'required_address_information' => []],
    'AM' => ['name' => 'Armenia', 'required_address_information' => []],
    'AW' => ['name' => 'Aruba', 'required_address_information' => []],
    'AU' => ['name' => 'Australia', 'required_address_information' => ['ZIP/postal code']],
    'AT' => ['name' => 'Austria', 'required_address_information' => []],
    'AZ' => ['name' => 'Azerbaijan', 'required_address_information' => []],
    'BS' => ['name' => 'Bahamas', 'required_address_information' => []],
    'BH' => ['name' => 'Bahrain', 'required_address_information' => []],
    'BD' => ['name' => 'Bangladesh', 'required_address_information' => []],
    'BB' => ['name' => 'Barbados', 'required_address_information' => []],
    'BE' => ['name' => 'Belgium', 'required_address_information' => []],
    'BZ' => ['name' => 'Belize', 'required_address_information' => []],
    'BJ' => ['name' => 'Benin', 'required_address_information' => []],
    'BM' => ['name' => 'Bermuda', 'required_address_information' => []],
    'BT' => ['name' => 'Bhutan', 'required_address_information' => []],
    'BO' => ['name' => 'Bolivia', 'required_address_information' => []],
    'BA' => ['name' => 'Bosnia and Herzegovina', 'required_address_information' => []],
    'BW' => ['name' => 'Botswana', 'required_address_information' => []],
    'BV' => ['name' => 'Bouvet Island', 'required_address_information' => []],
    'BR' => ['name' => 'Brazil', 'required_address_information' => []],
    'IO' => ['name' => 'British Indian Ocean Territory', 'required_address_information' => []],
    'VG' => ['name' => 'British Virgin Islands', 'required_address_information' => []],
    'BN' => ['name' => 'Brunei', 'required_address_information' => []],
    'BG' => ['name' => 'Bulgaria', 'required_address_information' => []],
    'BF' => ['name' => 'Burkina Faso', 'required_address_information' => []],
    'BI' => ['name' => 'Burundi', 'required_address_information' => []],
    'KH' => ['name' => 'Cambodia', 'required_address_information' => []],
    'CM' => ['name' => 'Cameroon', 'required_address_information' => []],
    'CA' => ['name' => 'Canada', 'required_address_information' => ['ZIP/postal code']],
    'CV' => ['name' => 'Cape Verde', 'required_address_information' => []],
    'BQ' => ['name' => 'Caribbean Netherlands (Bonaire, Sint Eustatius, and Saba)', 'required_address_information' => []],
    'KY' => ['name' => 'Cayman Islands', 'required_address_information' => []],
    'TD' => ['name' => 'Chad', 'required_address_information' => []],
    'CL' => ['name' => 'Chile', 'required_address_information' => []],
    'CN' => ['name' => 'China', 'required_address_information' => []],
    'CX' => ['name' => 'Christmas Island', 'required_address_information' => []],
    'CC' => ['name' => 'Cocos Islands', 'required_address_information' => []],
    'CO' => ['name' => 'Colombia', 'required_address_information' => []],
    'KM' => ['name' => 'Comoros', 'required_address_information' => []],
    'CK' => ['name' => 'Cook Islands', 'required_address_information' => []],
    'CR' => ['name' => 'Costa Rica', 'required_address_information' => []],
    'HR' => ['name' => 'Croatia', 'required_address_information' => []],
    'CW' => ['name' => 'Curaçao', 'required_address_information' => []],
    'CY' => ['name' => 'Cyprus', 'required_address_information' => []],
    'CZ' => ['name' => 'Czechia (Czech Republic)', 'required_address_information' => []],
    'CI' => ['name' => 'Côte d\'Ivoire (Ivory Coast)', 'required_address_information' => []],
    'DK' => ['name' => 'Denmark', 'required_address_information' => []],
    'DJ' => ['name' => 'Djibouti', 'required_address_information' => []],
    'DM' => ['name' => 'Dominica', 'required_address_information' => []],
    'DO' => ['name' => 'Dominican Republic', 'required_address_information' => []],
    'EC' => ['name' => 'Ecuador', 'required_address_information' => []],
    'EG' => ['name' => 'Egypt', 'required_address_information' => []],
    'SV' => ['name' => 'El Salvador', 'required_address_information' => []],
    'GQ' => ['name' => 'Equatorial Guinea', 'required_address_information' => []],
    'ER' => ['name' => 'Eritrea', 'required_address_information' => []],
    'EE' => ['name' => 'Estonia', 'required_address_information' => []],
    'ET' => ['name' => 'Ethiopia', 'required_address_information' => []],
    'FK' => ['name' => 'Falkland Islands', 'required_address_information' => []],
    'FO' => ['name' => 'Faroe Islands', 'required_address_information' => []],
    'FJ' => ['name' => 'Fiji', 'required_address_information' => []],
    'FI' => ['name' => 'Finland', 'required_address_information' => []],
    'FR' => ['name' => 'France', 'required_address_information' => ['ZIP/postal code']],
    'GF' => ['name' => 'French Guiana', 'required_address_information' => []],
    'PF' => ['name' => 'French Polynesia', 'required_address_information' => []],
    'TF' => ['name' => 'French Southern and Antarctic Lands', 'required_address_information' => []],
    'GA' => ['name' => 'Gabon', 'required_address_information' => []],
    'GM' => ['name' => 'Gambia', 'required_address_information' => []],
    'GE' => ['name' => 'Georgia', 'required_address_information' => []],
    'DE' => ['name' => 'Germany', 'required_address_information' => ['ZIP/postal code']],
    'GH' => ['name' => 'Ghana', 'required_address_information' => []],
    'GI' => ['name' => 'Gibraltar', 'required_address_information' => []],
    'GR' => ['name' => 'Greece', 'required_address_information' => []],
    'GL' => ['name' => 'Greenland', 'required_address_information' => []],
    'GD' => ['name' => 'Grenada', 'required_address_information' => []],
    'GP' => ['name' => 'Guadeloupe', 'required_address_information' => []],
    'GU' => ['name' => 'Guam', 'required_address_information' => []],
    'GT' => ['name' => 'Guatemala', 'required_address_information' => []],
    'GG' => ['name' => 'Guernsey', 'required_address_information' => []],
    'GN' => ['name' => 'Guinea', 'required_address_information' => []],
    'GW' => ['name' => 'Guinea-Bissau', 'required_address_information' => []],
    'GY' => ['name' => 'Guyana', 'required_address_information' => []],
    'HM' => ['name' => 'Heard Island and McDonald Islands', 'required_address_information' => []],
    'VA' => ['name' => 'Holy See (Vatican City)', 'required_address_information' => []],
    'HN' => ['name' => 'Honduras', 'required_address_information' => []],
    'HK' => ['name' => 'Hong Kong', 'required_address_information' => []],
    'HU' => ['name' => 'Hungary', 'required_address_information' => []],
    'IS' => ['name' => 'Iceland', 'required_address_information' => []],
    'IN' => ['name' => 'India', 'required_address_information' => ['ZIP/postal code']],
    'ID' => ['name' => 'Indonesia', 'required_address_information' => []],
    'IQ' => ['name' => 'Iraq', 'required_address_information' => []],
    'IE' => ['name' => 'Ireland', 'required_address_information' => []],
    'IM' => ['name' => 'Isle of Man', 'required_address_information' => []],
    'IL' => ['name' => 'Israel', 'required_address_information' => []],
    'IT' => ['name' => 'Italy', 'required_address_information' => ['ZIP/postal code']],
    'JM' => ['name' => 'Jamaica', 'required_address_information' => []],
    'JP' => ['name' => 'Japan', 'required_address_information' => []],
    'JE' => ['name' => 'Jersey', 'required_address_information' => []],
    'JO' => ['name' => 'Jordan', 'required_address_information' => []],
    'KZ' => ['name' => 'Kazakhstan', 'required_address_information' => []],
    'KE' => ['name' => 'Kenya', 'required_address_information' => []],
    'KI' => ['name' => 'Kiribati', 'required_address_information' => []],
    'XK' => ['name' => 'Kosovo', 'required_address_information' => []],
    'KW' => ['name' => 'Kuwait', 'required_address_information' => []],
    'KG' => ['name' => 'Kyrgyzstan', 'required_address_information' => []],
    'LA' => ['name' => 'Lao People\'s Democratic Republic (Laos)', 'required_address_information' => []],
    'LV' => ['name' => 'Latvia', 'required_address_information' => []],
    'LB' => ['name' => 'Lebanon', 'required_address_information' => []],
    'LS' => ['name' => 'Lesotho', 'required_address_information' => []],
    'LR' => ['name' => 'Liberia', 'required_address_information' => []],
    'LI' => ['name' => 'Liechtenstein', 'required_address_information' => []],
    'LT' => ['name' => 'Lithuania', 'required_address_information' => []],
    'LU' => ['name' => 'Luxembourg', 'required_address_information' => []],
    'MO' => ['name' => 'Macao', 'required_address_information' => []],
    'MK' => ['name' => 'Macedonia', 'required_address_information' => []],
    'MG' => ['name' => 'Madagascar', 'required_address_information' => []],
    'MW' => ['name' => 'Malawi', 'required_address_information' => []],
    'MY' => ['name' => 'Malaysia', 'required_address_information' => []],
    'MV' => ['name' => 'Maldives', 'required_address_information' => []],
    'MT' => ['name' => 'Malta', 'required_address_information' => []],
    'MH' => ['name' => 'Marshall Islands', 'required_address_information' => []],
    'MQ' => ['name' => 'Martinique', 'required_address_information' => []],
    'MR' => ['name' => 'Mauritania', 'required_address_information' => []],
    'MU' => ['name' => 'Mauritius', 'required_address_information' => []],
    'YT' => ['name' => 'Mayotte', 'required_address_information' => []],
    'MX' => ['name' => 'Mexico', 'required_address_information' => []],
    'FM' => ['name' => 'Micronesia', 'required_address_information' => []],
    'MD' => ['name' => 'Moldova', 'required_address_information' => []],
    'MC' => ['name' => 'Monaco', 'required_address_information' => []],
    'MN' => ['name' => 'Mongolia', 'required_address_information' => []],
    'ME' => ['name' => 'Montenegro', 'required_address_information' => []],
    'MS' => ['name' => 'Montserrat', 'required_address_information' => []],
    'MA' => ['name' => 'Morocco', 'required_address_information' => []],
    'MZ' => ['name' => 'Mozambique', 'required_address_information' => []],
    'NA' => ['name' => 'Namibia', 'required_address_information' => []],
    'NR' => ['name' => 'Nauru', 'required_address_information' => []],
    'NP' => ['name' => 'Nepal', 'required_address_information' => []],
    'NL' => ['name' => 'Netherlands', 'required_address_information' => ['ZIP/postal code']],
    'NC' => ['name' => 'New Caledonia', 'required_address_information' => []],
    'NZ' => ['name' => 'New Zealand', 'required_address_information' => []],
    'NE' => ['name' => 'Niger', 'required_address_information' => []],
    'NG' => ['name' => 'Nigeria', 'required_address_information' => []],
    'NU' => ['name' => 'Niue', 'required_address_information' => []],
    'NF' => ['name' => 'Norfolk Island', 'required_address_information' => []],
    'MP' => ['name' => 'Northern Mariana Islands', 'required_address_information' => []],
    'NO' => ['name' => 'Norway', 'required_address_information' => []],
    'OM' => ['name' => 'Oman', 'required_address_information' => []],
    'PK' => ['name' => 'Pakistan', 'required_address_information' => []],
    'PW' => ['name' => 'Palau', 'required_address_information' => []],
    'PS' => ['name' => 'Palestinian territories', 'required_address_information' => []],
    'PA' => ['name' => 'Panama', 'required_address_information' => []],
    'PG' => ['name' => 'Papua New Guinea', 'required_address_information' => []],
    'PY' => ['name' => 'Paraguay', 'required_address_information' => []],
    'PE' => ['name' => 'Peru', 'required_address_information' => []],
    'PH' => ['name' => 'Philippines', 'required_address_information' => []],
    'PN' => ['name' => 'Pitcairn', 'required_address_information' => []],
    'PL' => ['name' => 'Poland', 'required_address_information' => []],
    'PT' => ['name' => 'Portugal', 'required_address_information' => []],
    'PR' => ['name' => 'Puerto Rico', 'required_address_information' => []],
    'QA' => ['name' => 'Qatar', 'required_address_information' => []],
    'CG' => ['name' => 'Republic of Congo', 'required_address_information' => []],
    'RS' => ['name' => 'Republic of Serbia', 'required_address_information' => []],
    'RE' => ['name' => 'Reunion', 'required_address_information' => []],
    'RO' => ['name' => 'Romania', 'required_address_information' => []],
    'RW' => ['name' => 'Rwanda', 'required_address_information' => []],
    'BL' => ['name' => 'Saint Barthélemy', 'required_address_information' => []],
    'SH' => ['name' => 'Saint Helena', 'required_address_information' => []],
    'KN' => ['name' => 'Saint Kitts and Nevis', 'required_address_information' => []],
    'LC' => ['name' => 'Saint Lucia', 'required_address_information' => []],
    'MF' => ['name' => 'Saint Martin', 'required_address_information' => []],
    'PM' => ['name' => 'Saint Pierre and Miquelon', 'required_address_information' => []],
    'VC' => ['name' => 'Saint Vincent and the Grenadines', 'required_address_information' => []],
    'WS' => ['name' => 'Samoa', 'required_address_information' => []],
    'SM' => ['name' => 'San Marino', 'required_address_information' => []],
    'SA' => ['name' => 'Saudi Arabia', 'required_address_information' => []],
    'SN' => ['name' => 'Senegal', 'required_address_information' => []],
    'SC' => ['name' => 'Seychelles', 'required_address_information' => []],
    'SL' => ['name' => 'Sierra Leone', 'required_address_information' => []],
    'SG' => ['name' => 'Singapore', 'required_address_information' => []],
    'SX' => ['name' => 'Sint Maarten', 'required_address_information' => []],
    'SK' => ['name' => 'Slovakia', 'required_address_information' => []],
    'SI' => ['name' => 'Slovenia', 'required_address_information' => []],
    'SB' => ['name' => 'Solomon Islands', 'required_address_information' => []],
    'ZA' => ['name' => 'South Africa', 'required_address_information' => []],
    'GS' => ['name' => 'South Georgia and the South Sandwich Islands', 'required_address_information' => []],
    'KR' => ['name' => 'South Korea', 'required_address_information' => []],
    'ES' => ['name' => 'Spain', 'required_address_information' => ['ZIP/postal code']],
    'LK' => ['name' => 'Sri Lanka', 'required_address_information' => []],
    'SR' => ['name' => 'Suriname', 'required_address_information' => []],
    'SJ' => ['name' => 'Svalbard and Jan Mayen', 'required_address_information' => []],
    'SZ' => ['name' => 'Swaziland', 'required_address_information' => []],
    'SE' => ['name' => 'Sweden', 'required_address_information' => []],
    'CH' => ['name' => 'Switzerland', 'required_address_information' => []],
    'ST' => ['name' => 'São Tomé and Príncipe', 'required_address_information' => []],
    'TW' => ['name' => 'Taiwan', 'required_address_information' => []],
    'TJ' => ['name' => 'Tajikistan', 'required_address_information' => []],
    'TZ' => ['name' => 'Tanzania', 'required_address_information' => []],
    'TH' => ['name' => 'Thailand', 'required_address_information' => []],
    'TL' => ['name' => 'Timor-Leste', 'required_address_information' => []],
    'TG' => ['name' => 'Togo', 'required_address_information' => []],
    'TK' => ['name' => 'Tokelau', 'required_address_information' => []],
    'TO' => ['name' => 'Tonga', 'required_address_information' => []],
    'TT' => ['name' => 'Trinidad and Tobago', 'required_address_information' => []],
    'TN' => ['name' => 'Tunisia', 'required_address_information' => []],
    'TR' => ['name' => 'Turkey', 'required_address_information' => []],
    'TM' => ['name' => 'Turkmenistan', 'required_address_information' => []],
    'TC' => ['name' => 'Turks and Caicos Islands', 'required_address_information' => []],
    'TV' => ['name' => 'Tuvalu', 'required_address_information' => []],
    'VI' => ['name' => 'U.S. Virgin Islands', 'required_address_information' => []],
    'UG' => ['name' => 'Uganda', 'required_address_information' => []],
    'UA' => ['name' => 'Ukraine', 'required_address_information' => []],
    'AE' => ['name' => 'United Arab Emirates', 'required_address_information' => ['Region']],
    'GB' => ['name' => 'United Kingdom', 'required_address_information' => ['ZIP/postal code']],
    'US' => ['name' => 'United States', 'required_address_information' => ['ZIP/postal code']],
    'UM' => ['name' => 'United States Minor Outlying Islands', 'required_address_information' => []],
    'UY' => ['name' => 'Uruguay', 'required_address_information' => []],
    'UZ' => ['name' => 'Uzbekistan', 'required_address_information' => []],
    'VU' => ['name' => 'Vanuatu', 'required_address_information' => []],
    'VN' => ['name' => 'Vietnam', 'required_address_information' => []],
    'WF' => ['name' => 'Wallis and Futuna', 'required_address_information' => []],
    'EH' => ['name' => 'Western Sahara', 'required_address_information' => []],
    'ZM' => ['name' => 'Zambia', 'required_address_information' => []],
  ],
  'eu_countries' => [
    'AT' => ['name' => 'Austria', 'tax_rate' => 0.20],
    'BE' => ['name' => 'Belgium', 'tax_rate' => 0.21],
    'BG' => ['name' => 'Bulgaria', 'tax_rate' => 0.20],
    'HR' => ['name' => 'Croatia', 'tax_rate' => 0.25],
    'CY' => ['name' => 'Cyprus', 'tax_rate' => 0.19],
    'CZ' => ['name' => 'Czech Republic', 'tax_rate' => 0.21],
    'DK' => ['name' => 'Denmark', 'tax_rate' => 0.25],
    'EE' => ['name' => 'Estonia', 'tax_rate' => 0.22],
    'FI' => ['name' => 'Finland', 'tax_rate' => 0.24],
    'FR' => ['name' => 'France', 'tax_rate' => 0.20],
    'DE' => ['name' => 'Germany', 'tax_rate' => 0.19],
    'GR' => ['name' => 'Greece', 'tax_rate' => 0.24],
    'HU' => ['name' => 'Hungary', 'tax_rate' => 0.27],
    'IE' => ['name' => 'Ireland', 'tax_rate' => 0.23],
    'IT' => ['name' => 'Italy', 'tax_rate' => 0.22],
    'LV' => ['name' => 'Latvia', 'tax_rate' => 0.21],
    'LT' => ['name' => 'Lithuania', 'tax_rate' => 0.21],
    'LU' => ['name' => 'Luxembourg', 'tax_rate' => 0.17],
    'MT' => ['name' => 'Malta', 'tax_rate' => 0.18],
    'NL' => ['name' => 'Netherlands', 'tax_rate' => 0.21],
    'PL' => ['name' => 'Poland', 'tax_rate' => 0.23],
    'PT' => ['name' => 'Portugal', 'tax_rate' => 0.23],
    'RO' => ['name' => 'Romania', 'tax_rate' => 0.19],
    'SK' => ['name' => 'Slovak Republic', 'tax_rate' => 0.20],
    'SI' => ['name' => 'Slovenia', 'tax_rate' => 0.22],
    'ES' => ['name' => 'Spain', 'tax_rate' => 0.21],
    'SE' => ['name' => 'Sweden', 'tax_rate' => 0.25],
  ],
  'eu_prices' => [
    // EU's tax inclusive prices, this will override the prices configued in the plan
    Plan::INTERVAL_MONTH => 8.99,
    Plan::INTERVAL_YEAR => 97.00,
  ],
];
