<?php

/**
 * Siser Software
 * Siser software API specification.
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: shengtian.liao@iifuture.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace App\Mockup\Controllers;

use Illuminate\Support\Facades\Request;

class AuthenticationController extends \App\Http\Controllers\Controller
{
  /**
   * Constructor
   */
  public function __construct()
  {
  }

  /**
   * Operation authGetMe
   *
   * get signed-in user's information (stage 1).
   *
   */
  public function authGetMe()
  {
    $input = Request::all();

    //path params validation


    //not path params validation

    return response('How about implementing authGetMe as a get method ?');
  }
  /**
   * Operation authCreateToken
   *
   * create an access token (stage 1).
   *
   */
  public function authCreateToken()
  {
    $input = Request::all();

    //path params validation


    //not path params validation
    if (!isset($input['token_create_req'])) {
      throw new \InvalidArgumentException('Missing the required parameter $token_create_req when calling authCreateToken');
    }
    $token_create_req = $input['token_create_req'];


    return response('How about implementing authCreateToken as a post method ?');
  }
}
