<?php

/**
 * Siser Software
 * Siser software API specification.
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: shengtian.liao@iifuture.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace App\Mockup\Controllers;


use Illuminate\Support\Facades\Request;

class LDSSoftwareController extends \App\Http\Controllers\Controller
{
  /**
   * Constructor
   */
  public function __construct()
  {
  }

  /**
   * Operation softwareCheckIn
   *
   * LDS software check-in (stage 1).
   *
   */
  public function softwareCheckIn()
  {
    abort(400, 'Not implemented yet!');
  }
  /**
   * Operation softwareCheckInGet
   *
   * LDS software check-in (stage 1).
   *
   */
  public function softwareCheckInGet()
  {
    abort(400, 'Not implemented yet!');
  }
  /**
   * Operation softwareCheckOut
   *
   * LDS software check-out (stage 1).
   *
   */
  public function softwareCheckOut()
  {
    abort(400, 'Not implemented yet!');
  }
  /**
   * Operation softwareCheckOutGet
   *
   * LDS software check-out (stage 1).
   *
   */
  public function softwareCheckOutGet()
  {
    abort(400, 'Not implemented yet!');
  }
}
