<?php

/**
 * Siser Software
 * Siser software API specification.
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: shengtian.liao@iifuture.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace App\Mockup\Controllers;

use App\Mockup\Models\Repository;
use Illuminate\Support\Facades\Request;

class PublicController extends \App\Http\Controllers\Controller
{
  /**
   * Constructor
   */
  public function __construct(protected Repository $repo)
  {
  }

  /**
   * Operation listPlan
   *
   * list plan (stage 2+).
   *
   */
  public function listPlan()
  {
    return response()->json(['data' => $this->repo->getPlans()]);
  }
  /**
   * Operation getPlan
   *
   * get plan by id (stage 2+).
   *
   * @param int $id  (required)
   */
  public function getPlan($id)
  {
    return response()->json($this->repo->getPlan($id));
  }
  /**
   * Operation listSoftwarePackages
   *
   * retrieves software packages and their download url (stage 1).
   *
   */
  public function listSoftwarePackages()
  {
    return response()->json(['data' => $this->repo->getSoftwarePackages()]);
  }
  /**
   * Operation getSoftwarePackage
   *
   * retrieves one software package and their download url (stage 1).
   *
   * @param int $id  (required)
   */
  public function getSoftwarePackage($id)
  {
    return response()->json($this->repo->getSoftwarePackage($id));
  }
}
