<?php

/**
 * Siser Software
 * Siser software API specification.
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: shengtian.liao@iifuture.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace App\Mockup\Controllers;

use App\Mockup\Models\Repository;
use Illuminate\Support\Facades\Request;

class TestController extends \App\Http\Controllers\Controller
{
  /**
   * Constructor
   */
  public function __construct(protected Repository $repo)
  {
  }

  /**
   * Operation commonErrorExample
   *
   * example for error response.
   *
   */
  public function commonErrorExample()
  {
    $input = Request::all();

    //path params validation


    //not path params validation
    $code = $input['code'] ?? "200";

    if ($code == "200") {
      return;
    } else {
      return response()->json(['message' => "error code is $code"], $code);
    }
  }
  /**
   * Operation testReset
   *
   * reset test data.
   */
  public function testReset()
  {
    $this->repo->reset();
  }
}
